// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IRS.Models
{
    public partial class DispatchListDetail
    {
        public int Id { get; set; }
        public int DispatchListId { get; set; }
        public int MixingInfoId { get; set; }
        public DateTime CreatedTime { get; set; }
    }
}