// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IRS.Models
{
    public partial class InkTblObject
    {
        //public InkTblObject()
        //{
        //    Schedules = new HashSet<Schedule>();
        //}

        public int Id { get; set; }
        public string Name { get; set; }
        public int ProcessId { get; set; }

        public virtual Process Process { get; set; }
    }
}