// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IRS.Models
{
    public partial class PoGlue
    {
        public Guid? Id { get; set; }
        public int? ScheduleId { get; set; }
        public int? GlueId { get; set; }
        public bool? Status { get; set; }
        public int? WorkPlanId { get; set; }
        public DateTime? CreatedTime { get; set; }
        public int? PartId { get; set; }
    }
}