// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IRS.Models
{
    public partial class Process
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int? SupplierID { get; set; }
        public string Color { get; set; }
        public string Guid { get; set; }

        public virtual ICollection<Ink> Inks { get; set; }
        public virtual ICollection<InkTblObject> InkTblObjects { get; set; }
    }
}