// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IRS.Models
{
    public partial class SchedulesUpdate
    {
        public int Id { get; set; }
        public string ModelName { get; set; }
        public string ModelNo { get; set; }
        public string ArticleNo { get; set; }
        public string Treatment { get; set; }
        public string Process { get; set; }
        public bool ApprovalStatus { get; set; }
        public bool FinishedStatus { get; set; }
        public int ApprovalBy { get; set; }
        public int CreatedBy { get; set; }
        public string Season { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime ProductionDate { get; set; }
        public DateTime? EstablishDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public DateTime? UpdateTime { get; set; }
        public DateTime? CreatedTime { get; set; }
    }
}