// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IRS.Models
{
    public partial class SettingWorkPlan
    {
        public int Id { get; set; }
        public string Po { get; set; }
        public string ModelName { get; set; }
        public string ModelNo { get; set; }
        public string ArtNo { get; set; }
        public int PartId { get; set; }
        public string Building { get; set; }
        public double? Total { get; set; }
        public DateTime? DueDate { get; set; }
        public DateTime? CreatedTime { get; set; }
        public int? CreatedBy { get; set; }
        public int? DeleteBy { get; set; }
        public DateTime? DeleteTime { get; set; }
    }
}