// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IRS.Models
{
    public partial class Supplier
    {
        public Supplier()
        {
            Inks = new HashSet<Ink>();
            Processes = new HashSet<Process>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Guid { get; set; }
        public int ModifiedBy { get; set; }
        public DateTime ModifiedDate { get; set; }
        public bool? IsShow { get; set; }
        public int ProcessId { get; set; }

        public virtual ICollection<Ink> Inks { get; set; }
        public virtual ICollection<Process> Processes { get; set; }
    }
}