// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IRS.DTO
{
    public partial class SupplierDto
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Process { get; set; }
        public string Guid { get; set; }
        public int ProcessID { get; set; }
    }
}