// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IRS.DTO
{
    public partial class TreatmentWorkPlanDto
    {
        public int ID { get; set; }
        public string Treatment { get; set; }
        public bool Status { get; set; }
        public bool FinishedStatus { get; set; }
        public string Color { get; set; }
    }
}