// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using IRS.Models3;

#nullable disable

namespace IRS.Data
{
    public partial class Pigfarm3Context : DbContext
    {
        public Pigfarm3Context()
        {
        }

        public Pigfarm3Context(DbContextOptions<Pigfarm3Context> options)
            : base(options)
        {
        }

        public virtual DbSet<Schedule> Schedules { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.Entity<Schedule>(entity =>
            {
                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.ColorGuid)
                    .HasMaxLength(50)
                    .HasColumnName("COLOR_GUID");

                entity.Property(e => e.Consumption).HasColumnName("CONSUMPTION");

                entity.Property(e => e.CreateBy)
                    .HasColumnType("numeric(18, 0)")
                    .HasColumnName("CREATE_BY");

                entity.Property(e => e.CreateDate)
                    .HasColumnType("datetime")
                    .HasColumnName("CREATE_DATE");

                entity.Property(e => e.DeleteBy)
                    .HasColumnType("numeric(18, 0)")
                    .HasColumnName("DELETE_BY");

                entity.Property(e => e.DeleteDate)
                    .HasColumnType("datetime")
                    .HasColumnName("DELETE_DATE");

                entity.Property(e => e.Guid)
                    .HasMaxLength(50)
                    .HasColumnName("GUID");

                entity.Property(e => e.PartGuid)
                    .HasMaxLength(50)
                    .HasColumnName("PART_GUID");

                entity.Property(e => e.ProcessGuid)
                    .HasMaxLength(50)
                    .HasColumnName("PROCESS_GUID");

                entity.Property(e => e.ShoeGuid)
                    .HasMaxLength(50)
                    .HasColumnName("SHOE_GUID");

                entity.Property(e => e.Status)
                    .HasColumnType("numeric(18, 0)")
                    .HasColumnName("STATUS");

                entity.Property(e => e.TreatmentGuid)
                    .HasMaxLength(50)
                    .HasColumnName("TREATMENT_GUID");

                entity.Property(e => e.TreatmentWayGuid)
                    .HasMaxLength(50)
                    .HasColumnName("TREATMENT_WAY_GUID");

                entity.Property(e => e.UpdateBy)
                    .HasColumnType("numeric(18, 0)")
                    .HasColumnName("UPDATE_BY");

                entity.Property(e => e.UpdateDate)
                    .HasColumnType("datetime")
                    .HasColumnName("UPDATE_DATE");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}