// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IRS.Models
{
    public partial class ColorWorkPlan
    {
        public int Id { get; set; }
        // public decimal Id { get; set; }
        public string Guid { get; set; }
        public string ShoeGuid { get; set; }
        public DateTime? CreateDate { get; set; }
        // public string CreateBy { get; set; }
        public decimal? CreateBy { get; set; }
        public DateTime? ExecuteDate { get; set; }
        public int Active { get; set; }
    }
}