// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IRS.Models
{
    public partial class ColorTodo
    {
        public int Id { get; set; }
        public Guid Guid { get; set; }
        public string ColorWorkPlanGuid { get; set; }
        public DateTime? ExecuteDate { get; set; }
        public decimal? ExecuteAmount { get; set; }
        public string SchedulesGuid { get; set; }
        public int? IsFinished { get; set; }
        public DateTime? FinishedTime { get; set; }
        public int? IsPending { get; set; }
        public decimal? FinishedBy { get; set; }
    }
}