// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IRS.Models
{
    public partial class DispatchList
    {
        public int Id { get; set; }
        public int PlanId { get; set; }
        public int MixingInfoId { get; set; }
        public int GlueId { get; set; }
        public int GlueNameId { get; set; }
        public int BuildingId { get; set; }
        public int LineId { get; set; }
        public int Bpfcid { get; set; }
        public string LineName { get; set; }
        public string GlueName { get; set; }
        public string Supplier { get; set; }
        public bool Status { get; set; }
        public DateTime? StartDispatchingTime { get; set; }
        public DateTime? FinishDispatchingTime { get; set; }
        public DateTime? PrintTime { get; set; }
        public DateTime EstimatedStartTime { get; set; }
        public DateTime EstimatedFinishTime { get; set; }
        public bool IsDelete { get; set; }
        public DateTime DeleteTime { get; set; }
        public int DeleteBy { get; set; }
        public int ColorCode { get; set; }
        public DateTime FinishTimeOfPeriod { get; set; }
        public DateTime StartTimeOfPeriod { get; set; }
        public bool? AbnormalStatus { get; set; }
        public int CreatedBy { get; set; }
        public DateTime CreatedTime { get; set; }
        public double DeliveredAmount { get; set; }
    }
}