// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IRS.Models
{
    public partial class Ink
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime ManufacturingDate { get; set; }
        public string MaterialNo { get; set; }
        public double Unit { get; set; }
        public int SupplierId { get; set; }
        public string Voc { get; set; }
        public int CreatedBy { get; set; }
        public int ExpiredTime { get; set; }
        public int DaysToExpiration { get; set; }
        public bool IsShow { get; set; }
        public int ModifiedBy { get; set; }
        public DateTime ModifiedDate { get; set; }
        public int ProcessId { get; set; }
        public double Percentage { get; set; }
        public string NameEn { get; set; }
        public string Guid { get; set; }
        public virtual Process Process { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}