// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IRS.Models
{
    public partial class SchedulePart
    {
        public int Id { get; set; }
        public int ScheduleId { get; set; }
        public int PartId { get; set; }
        public DateTime CreatedDate { get; set; }
    }
}