// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IRS.Models
{
    public partial class Stock
    {
        public int Id { get; set; }
        public int InkOrChemicalId { get; set; }
        public string Code { get; set; }
        public string NameInkOrChemical { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime CreatedTime { get; set; }
        public DateTime ManufacturingDate { get; set; }
        public string SupplierName { get; set; }
        public string Batch { get; set; }
        public DateTime ExpiredTime { get; set; }
        public int Unit { get; set; }
        public int UserId { get; set; }
        public string BuildingName { get; set; }
        public bool Status { get; set; }
        public string SubName { get; set; }
    }
}