// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IRS.DTO
{
    public partial class ColorUploadDto
    {
        public int GlueID { get; set; }
        public string Name { get; set; }
        public int InkID { get; set; }
        public int ChemicalID { get; set; }
        public string Percentage { get; set; }

    }
}