// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IRS.DTO
{
    public partial class ScheduleUploadDto
    {
        public int ScheduleID { get; set; }
        public int GlueID { get; set; }
        public int TreatmentWayID { get; set; }
        public string ModelName { get; set; }
        public string ModelNo { get; set; }
        public string ArticelNo { get; set; }
        public string Treatment { get; set; }
        public string Process { get; set; }
        public string Name { get; set; }
        public string Consumption { get; set; }
        public string Part { get; set; }

    }
}