// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IRS.DTO
{
    public partial class StockInInkFilterRequestDto
    {
        public DateTime? executionDate { get; set; }
        public DateTime? createDate { get; set; }
    }
}